# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Sticker' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Sticker
  pod 'Alamofire'
  pod 'SDWebImage'
  pod 'MBProgressHUD', '~> 1.1.0'
  pod 'SwiftyJSON'
  pod 'Google-Mobile-Ads-SDK'
  pod 'SDWebImageWebPCoder'
  pod 'OneSignal', '>= 3.0.0', '< 4.0'
  
  
end

target 'OneSignalNotificationServiceExtension' do
  use_frameworks!
  pod 'OneSignal', '>= 3.0.0', '< 4.0'
end
